# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kMeans <- function(inputMatrix, k, epsilon, maxIter) {
    .Call('KM_kMeans', PACKAGE = 'KM', inputMatrix, k, epsilon, maxIter)
}

