# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kmeans <- function(inputMatrix, k, epsilon, maxIter) {
    .Call('KM_kmeans', PACKAGE = 'KM', inputMatrix, k, epsilon, maxIter)
}

kOmeans <- function(inputMatrix, k, epsilon, maxIter, omega) {
    .Call('KM_kOmeans', PACKAGE = 'KM', inputMatrix, k, epsilon, maxIter, omega)
}

betterKmeans <- function(inputMatrix, k, epsilon, maxIter, omega, expression, drawPoints) {
    .Call('KM_betterKmeans', PACKAGE = 'KM', inputMatrix, k, epsilon, maxIter, omega, expression, drawPoints)
}

